### ISSUE TITLE
Doent work!

### ISSUE THREAD

**Issue by murataygunn** [G33kDude/Chrome.ahk#19]
Just clone and run an example.

**Comment by G33kDude** [comment]
In what way does it not work? Did you also initialize/update the required submodules? Git does not pull submodules with the main repository by default, so you must either run the appropriate command to grab submodules, or use the released version which has all submodules/dependencies baked in.

**Comment by murataygunn** [comment]
I've used this comman to clone;
git clone --recurse-submodules https://github.com/G33kDude/Chrome.ahk.git

It downloaded submodules as well. No problem here.

When i try to run the pastebin example i get this error;


![image](https://user-images.githubusercontent.com/17836269/102989609-f49dfb00-4526-11eb-9caa-fe200049861d.png)

I've tried different computers as well. Same issue. Latest AHK 1.1.33.02 vers. AutoHotkeyU64.exe installed.

**Comment by murataygunn** [comment]
Release version works ok.

**Comment by mark-wiemer** [comment]
I've fixed this in my fork: [mark-wiemer/Chrome.ahk](https://github.com/mark-wiemer/Chrome.ahk)

**Comment by tenbob** [comment]
It would be helpful if the OP had said what the problem was in the title. It should really be "Call to nonexistent function Jxon_Dump()". I had the same problem. I don't fully understand the code, but it looks like the function is being executed inside its own definition. Is that right?

Thanks to @mark-wiemer who has solved this problem in his fork [mark-wiemer/Chrome.ahk](https://github.com/mark-wiemer/Chrome.ahk). @mark-wiemer also solved another problem which is a fatal error when the debug message contains a boolean value.

I don't see a Pull Request to bring this into the main branch. Without these changes the program seems to be unusable. Can someone make a PR, please.
